path:
  data:
    input: '../data/input/유튜브_음식_19596.mp4' # raw data input
    preprocessing_output: '../data/output/preprocessing_유튜브_음식_19596.mp4'
    timeline_output: '../data/output/timeline_유튜브_음식_19596.mp4'
    shorts_output: '../data/short_clips/'
    eda_input: '../data/input/유튜브_음식_19596.mp4'
    eda_output: '../data/output/eda_유튜브_음식_19596.png'
  log:
    preprocessing_log: '../log/processing_info_유튜브_음식_19596.txt'
    timeline_log: '../log/timeline_info_유튜브_음식_19596.txt'

train:
  input_path: '../data/train/'
  output_path: '../output/'

preprocessing:
  brightness_bool: False
  motion_bool: False
  noise_bool: False
  quality_threshold: 30
  brightness_threshold: 30
  motion_threshold: 30
  noise_threshold: 30